// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jytyfafucoevezzjbyrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5dHlmYWZ1Y29ldmV6empieXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODM3NTAsImV4cCI6MjA3NDE1OTc1MH0.Fb422s64SxGxZqY3WEw2yNu9ouYrQrXz_RzSN6JZ3oc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});